import type { SiteContent } from './types';

export const en: SiteContent = {
  locale: 'en',
  dir: 'ltr',
  meta: {
    title: 'FreshSpaces | Premium Home & Villa Cleaning in Riyadh, Saudi Arabia',
    description:
      'From chaos to spotless. Premium deep cleaning for villas, apartments and offices across Riyadh: vetted specialists, eco-certified products and a spotless result, guaranteed.',
    shareTitle: 'FreshSpaces | Home & Villa Cleaning in Riyadh',
    shareAlt: 'FreshSpaces: from chaos to spotless. Home and villa cleaning in Riyadh.',
    ogLocale: 'en_SA',
  },
  lang: { label: 'العربية', href: '/ar', aria: 'View this site in Arabic' },
  header: { tagline: 'Riyadh, Saudi Arabia', city: 'Riyadh', book: 'Book Cleaning', call: 'Call', menu: 'Toggle menu' },
  nav: { services: 'Services', results: 'Before & After', howItWorks: 'How It Works', reviews: 'Reviews', contact: 'Contact' },
  hero: {
    eyebrow: 'Home & villa cleaning in Riyadh',
    line1: 'From chaos',
    to: 'to ',
    word: 'spotless.',
    description: 'Deep cleaning for villas and apartments across Riyadh: vetted specialists, eco-certified products and a spotless result, guaranteed.',
    ratingAria: '4.9 out of 5 stars',
    homes: '1,200+ homes cleaned',
    sameDay: 'Same-day service',
    promises: ['Licensed CR #101089201', 'Vetted & insured team', 'Eco-certified products', '100% satisfaction guarantee'],
  },
  services: {
    eyebrow: 'What we do',
    title: 'Services',
    intro: '30+ years of professional cleaning expertise tailored to luxury homes, villas, and corporate offices across every corner of Riyadh.',
    book: 'Book this service',
    prev: 'Previous Service',
    next: 'Next Service',
    goTo: 'Go to slide {n}',
    items: [
      {
        title: 'Villa Deep Cleaning',
        category: 'Residential',
        description: 'Comprehensive deep steam sanitation, kitchen degreasing, and detailed room scrubbing for luxury Riyadh villas.',
        badge: 'Popular Choice',
        features: ['High-temp Steam Sanitization', 'Full Kitchen Degreasing', 'Balcony & Patio Power Wash'],
      },
      {
        title: 'Post-Construction Restoration',
        category: 'Commercial & Residential',
        description: 'Complete removal of plaster dust, grout film, paint splatters, and construction debris for new handovers.',
        badge: 'Heavy Duty',
        features: ['Paint Splatter Removal', 'Industrial HEPA Dust Extraction', 'Window Track Scrubbing'],
      },
      {
        title: 'Upholstery & Carpet Steam Care',
        category: 'Specialized',
        description: 'Deep hot-water extraction destroying 99.9% of dust mites, deep-seated stains, and desert dust from sofas & rugs.',
        badge: 'Allergen Free',
        features: ['Organic Stain Neutralizer', 'Fabric Fiber Protection', 'Rapid 2-Hour Dry Time'],
      },
      {
        title: 'Marble & Stone Floor Polishing',
        category: 'Restoration',
        description: 'Diamond pad honing, crystallization, and high-gloss sealing to restore mirror clarity on Saudi marble floors.',
        badge: 'Mirror Finish',
        features: ['Diamond Disc Grinding', 'Anti-Slip Gloss Crystallization', 'Sealant Stain Guard'],
      },
      {
        title: 'Facade & Window Cleaning',
        category: 'Exterior',
        description: 'High-reach deionized pure water glass washing for spotless streak-free panoramic windows and building exteriors.',
        badge: 'Streak-Free',
        features: ['Deionized Pure Water', 'High-Reach Water Pole System', 'Solar Panel Cleaning'],
      },
      {
        title: 'Disinfection & Sanitization',
        category: 'Health & Safety',
        description: 'Hospital-grade electrostatic fogging and anti-viral misting for safe, germ-free homes, offices, and schools.',
        badge: 'Certified Safe',
        features: ['Non-Toxic Eco Misting', 'Hospital-Grade Disinfectant', 'Safe for Children & Pets'],
      },
    ],
  },
  beforeAfter: {
    eyebrow: 'The difference',
    line1: 'Same room.',
    soft: 'two hours ',
    bold: 'apart.',
    intro: 'Drag across the room to wipe away the before. Every job ends with a walkthrough, and nothing is signed off until it looks like this.',
    roomsLabel: 'Rooms',
    after: 'After',
    before: 'Before',
    drag: 'Drag to clean',
    sliderAria: 'Before and after comparison: move left or right',
    beforeAlt: '{room} before cleaning',
    afterAlt: '{room} after cleaning',
    rooms: [
      { label: 'Living room', place: 'Villa · Al Nakheel', time: '3h 20m', team: '2 specialists', work: 'Rug shampoo, upholstery steam, glass & skirting detail' },
      { label: 'Kitchen', place: 'Apartment · Al Olaya', time: '2h 45m', team: '2 specialists', work: 'Degreasing, appliance detail, counter & floor restoration' },
      { label: 'Bathroom', place: 'Villa · Hittin', time: '1h 50m', team: '1 specialist', work: 'Limescale & mildew removal, grout and glass polish' },
    ],
  },
  howItWorks: {
    eyebrow: 'How it works',
    line1: 'Three steps.',
    soft: 'zero ',
    bold: 'effort.',
    intro: 'Booking takes two minutes. Everything after that is on us.',
    steps: [
      {
        title: 'Book in two minutes',
        text: 'Choose the service, your district and a time that suits you. You get a fixed price up front. No calls, no surprises.',
        points: ['Same-day slots across Riyadh', 'Fixed, transparent pricing'],
      },
      {
        title: 'We arrive and transform',
        text: 'A vetted, insured team arrives fully equipped: industrial steam, HEPA extraction and eco-certified products.',
        points: ['Background-checked specialists', 'Safe for children and pets'],
      },
      {
        title: 'Walk into spotless',
        text: 'We finish with a walkthrough together. If anything is less than perfect, we come back and re-clean it free within 24 hours.',
        points: ['Room-by-room inspection', '100% satisfaction guarantee'],
      },
    ],
  },
  testimonials: {
    eyebrow: 'Kind words',
    outOf: 'out of 5',
    from: 'from 1,200+ homes in Riyadh',
    quoteMark: '“',
    showReview: 'Show review from {name}',
    prev: 'Previous review',
    next: 'Next review',
    starsAria: '{n} out of 5 stars',
    reviews: [
      { name: 'Noura A.', place: 'Villa · Hittin', service: 'Villa deep clean', quote: 'They gave us back the house we moved into. Every corner, every grout line, even the majlis carpets look new again.' },
      { name: 'Faisal M.', place: 'Apartment · Al Olaya', service: 'Move-out clean', quote: 'Booked at nine, the team was at my door before eleven. My landlord asked who I’d hired and kept the number.' },
      { name: 'Sarah K.', place: 'Villa · Al Malqa', service: 'Post-construction', quote: 'After six months of renovation dust I had honestly given up. Two days later the whole villa was spotless, and quiet.' },
      { name: 'Abdullah R.', place: 'Office · King Fahd Road', service: 'Weekly office care', quote: 'Our office has never felt this fresh. Discreet, always on time, and the same trusted crew every single week.' },
      { name: 'Lina H.', place: 'Villa · Al Yasmin', service: 'Marble & upholstery', quote: 'The marble floors gleam like a hotel lobby. The sofa my kids live on? You would never know.' },
    ],
    snippets: [
      ['Like moving into a new villa.', 'Noura · Hittin'],
      ['On time, every time.', 'Abdullah · Olaya'],
      ['The majlis smells like the first day.', 'Reem · Al Narjis'],
      ['Worth every riyal.', 'Faisal · Al Olaya'],
      ['My mother noticed the windows first.', 'Omar · Al Rabwah'],
      ['Spotless and genuinely kind people.', 'Sarah · Al Malqa'],
    ],
  },
  booking: {
    eyebrow: 'Riyadh premier cleaning specialists',
    line1: 'Transform your space',
    soft: 'in just ',
    bold: 'one hour.',
    intro:
      'Book Riyadh’s top-rated deep cleaning team. We bring specialized industrial equipment, eco-certified detergents, and 100% satisfaction guarantee to your doorstep.',
    props: [
      { title: 'Same-Day Dispatch', text: 'Quick arrival across all Riyadh districts within 90 minutes.' },
      { title: '100% Satisfaction', text: "Free re-clean guarantee if any spot doesn't sparkle." },
    ],
    address: 'King Fahd Road, Al Olaya, Riyadh 12211, Saudi Arabia',
    formTitle: 'Book FreshSpaces Cleaning',
    formIntro: 'Get an instant quote and priority dispatch date.',
    name: 'Your Name',
    namePlaceholder: 'e.g. Osama Tillo',
    phone: 'Mobile Number',
    district: 'Riyadh District',
    districts: ['Al Malqa, Riyadh', 'Al Nakheel, Riyadh', 'Hittin, Riyadh', 'Al Olaya, Riyadh', 'Al Yasmin, Riyadh', 'Other Riyadh Location'],
    service: 'Service Type',
    notes: 'Special Requests (Optional)',
    notesPlaceholder: 'Specify size of property, number of bedrooms, or specific requirements...',
    submit: 'Confirm Cleaning Booking',
    doneTitle: 'Booking Request Received!',
    done: ['Thank you, ', '. Our Riyadh dispatch team will call you at ', ' within 15 minutes.'],
    again: 'Submit Another Request',
  },
  footer: {
    servicesTitle: 'Services',
    hqTitle: 'Riyadh Dispatch HQ',
    address: 'King Fahd Road, Al Olaya District, Riyadh, Kingdom of Saudi Arabia',
    hotline: '24/7 Emergency Cleaning Hotline',
    licensed: 'Licensed Saudi Commercial CR #101089201',
    backToTop: 'Back to top',
  },
};
