import type { SiteContent } from './types';

export const en: SiteContent = {
  locale: 'en',
  dir: 'ltr',
  meta: {
    title: 'FreshSpaces | Premium Home & Villa Cleaning in Riyadh, Saudi Arabia',
    description:
      'From chaos to spotless. Premium deep cleaning for villas, apartments and offices across Riyadh: vetted specialists, eco-certified products and a spotless result, guaranteed.',
    shareTitle: 'FreshSpaces | Home & Villa Cleaning in Riyadh',
    shareAlt: 'FreshSpaces: from chaos to spotless. Home and villa cleaning in Riyadh.',
    ogLocale: 'en_SA',
  },
  lang: { label: 'العربية', href: '/ar', aria: 'View this site in Arabic' },
  header: { tagline: 'Riyadh, Saudi Arabia', book: 'Book Cleaning', call: 'Call', menu: 'Toggle menu' },
  nav: { services: 'Services', results: 'Before & After', howItWorks: 'How It Works', reviews: 'Reviews', contact: 'Contact' },
  hero: {
    eyebrow: 'Cleaning & maintenance in Riyadh',
    line1: 'Cleaned, fixed',
    to: 'and ',
    word: 'cared for.',
    description:
      'Professional cleaning, home maintenance and office maintenance across Riyadh: one vetted, insured team for villas, apartments and offices, with a spotless result, guaranteed.',
    ratingAria: '4.9 out of 5 stars',
    homes: '1,200+ homes cleaned',
    sameDay: 'Same-day service',
    promises: ['Licensed CR #101089201', 'Vetted & insured team', 'Eco-certified products', '100% satisfaction guarantee'],
  },
  services: {
    cleaning: {
      eyebrow: 'Cleaning',
      title: 'Cleaning services',
      intro: 'Deep, detailed cleaning for villas, apartments and offices across Riyadh.',
      cta: 'View All Cleaning Services',
      items: [
        { title: 'Villa Deep Cleaning', description: 'A room-by-room deep clean with steam sanitizing, kitchen degreasing and careful detail work.' },
        { title: 'Upholstery & Carpet Care', description: 'Hot-water extraction that lifts stains, dust mites and desert dust from sofas and rugs.' },
        { title: 'Post-Construction Cleaning', description: 'Plaster dust, paint splatter and debris cleared away, ready for handover.' },
      ],
    },
    maintenance: {
      eyebrow: 'Maintenance',
      title: 'Home maintenance & repairs',
      intro: 'Trusted technicians for the jobs that keep a home running well.',
      cta: 'View All Maintenance Services',
      items: [
        { title: 'AC Maintenance', description: 'Cleaning, gas top-ups and repairs for split and central units, before the summer heat.' },
        { title: 'Plumbing Repairs', description: 'Leaks, blockages, water heaters and fittings fixed quickly and neatly.' },
        { title: 'Electrical Repairs', description: 'Lighting, sockets and fault finding, handled by licensed electricians.' },
      ],
    },
  },
  servicesPage: {
    meta: {
      title: 'Services | FreshSpaces Cleaning & Home Maintenance in Riyadh',
      description:
        'Cleaning services and home maintenance & repairs across Riyadh: villa deep cleaning, upholstery, marble polishing, AC maintenance, plumbing, electrical and more.',
    },
    eyebrow: 'Our services',
    line1: 'Everything your home needs,',
    soft: 'from one trusted ',
    bold: 'team.',
    intro: 'Two kinds of care, kept clearly apart: cleaning for every room, and maintenance & repairs for everything that keeps a home running.',
    cleaningMore: [
      { title: 'Disinfection & Sanitizing', description: 'Electrostatic fogging with non-toxic, hospital-grade disinfectant for homes, nurseries and offices.' },
      { title: 'Facade & Window Cleaning', description: 'Pure-water, high-reach washing for streak-free windows, glass facades and frames.' },
      { title: 'Marble Floor Polishing', description: 'Honing, crystallization and sealing that bring a mirror shine back to marble and stone.' },
      { title: 'Kitchen Deep Cleaning', description: 'Range hoods, ovens, cabinets and tiles degreased and detailed, inside and out.' },
      { title: 'Move-In & Move-Out Cleaning', description: 'An empty home cleaned top to bottom, ready for new keys or a full deposit back.' },
    ],
    maintenanceMore: [
      { title: 'Painting & Wall Repairs', description: 'Cracks filled, walls sanded and repainted with a clean, even finish and no mess left behind.' },
      { title: 'Carpentry & Door Repairs', description: 'Sticking doors, loose hinges, cabinets and wardrobes adjusted, repaired or refitted.' },
      { title: 'Appliance Repairs', description: 'Washing machines, dryers, fridges and ovens diagnosed and repaired at home.' },
      { title: 'Tiling & Grout Repairs', description: 'Cracked tiles replaced and tired grout renewed in bathrooms, kitchens and floors.' },
      { title: 'Mounting & Installations', description: 'TVs, shelves, curtains and light fixtures installed level, secure and neat.' },
    ],
    cta: {
      eyebrow: 'Book a call or an appointment',
      line1: 'Not sure where to start?',
      soft: 'We are here ',
      bold: 'to help.',
      intro:
        'Call us and a specialist will help you choose the right service for your home, or book an appointment and we will confirm a time that suits you, often on the same day.',
      book: 'Book an appointment',
      call: 'Call a specialist',
    },
  },
  about: {
    eyebrow: 'About us',
    line1: 'Built in Riyadh,',
    soft: 'for Riyadh ',
    bold: 'homes.',
    intro:
      'FreshSpaces is a Riyadh home services company. One trusted team cleans, maintains and repairs villas and apartments across the city, so everything your home needs starts with one call.',
    points: [
      { label: 'Company', title: 'Licensed and local', text: 'A registered Saudi company (CR #101089201) with a dispatch HQ on King Fahd Road and teams in every district.' },
      { label: 'Team', title: 'People you can trust at home', text: 'Every specialist and technician is background-checked, trained in-house and insured before their first visit.' },
      { label: 'Service', title: 'Care from start to finish', text: 'Clear communication, careful work and a walkthrough at the end of every job, with a free re-clean if anything is missed.' },
    ],
    alts: ['Polishing the marble floor of a villa entrance hall', 'A FreshSpaces specialist sanitizing a child’s room', 'A FreshSpaces technician repairing a washing machine'],
  },
  faq: {
    eyebrow: 'FAQ',
    line1: 'Questions,',
    soft: 'simply ',
    bold: 'answered.',
    intro: 'The things clients ask us most. For anything else, our team is one call away.',
    items: [
      { q: 'Which areas of Riyadh do you cover?', a: 'Every district in Riyadh, from Al Malqa and Hittin to Al Olaya and Al Yasmin, with same-day slots in most areas.' },
      {
        q: 'Do I need to be home during the visit?',
        a: 'Not necessarily. Many clients leave a key or door code. A supervisor confirms arrival and finish with you by phone, and the final walkthrough can be done on a video call.',
      },
      {
        q: 'Do you bring your own equipment and products?',
        a: 'Yes. Every team arrives fully equipped with industrial steam, HEPA extraction and eco-certified products. You do not need to provide anything.',
      },
      { q: 'Are your products safe for children and pets?', a: 'Yes. We use eco-certified, non-toxic products, and we can switch to fragrance-free options on request.' },
      {
        q: 'Do you handle repairs as well as cleaning?',
        a: 'Yes. Our maintenance team covers AC, plumbing, electrical, painting, carpentry and more, so one call takes care of the whole home.',
      },
      {
        q: 'Are your cleaners and technicians vetted?',
        a: 'Every team member is background-checked, trained in-house and insured. Electrical and AC work is done by licensed technicians.',
      },
      { q: 'What if I am not happy with the result?', a: 'Tell us within 24 hours and we will come back and re-clean that area free of charge. That is our satisfaction guarantee.' },
      { q: 'How do I book?', a: 'Fill in the booking form or call us. We confirm a time with you and send the team, often on the same day.' },
    ],
  },
  beforeAfter: {
    eyebrow: 'The difference',
    line1: 'Same room.',
    soft: 'two hours ',
    bold: 'apart.',
    intro: 'Drag across the room to wipe away the before. Every job ends with a walkthrough, and nothing is signed off until it looks like this.',
    roomsLabel: 'Rooms',
    after: 'After',
    before: 'Before',
    drag: 'Drag to clean',
    sliderAria: 'Before and after comparison: move left or right',
    beforeAlt: '{room} before cleaning',
    afterAlt: '{room} after cleaning',
    rooms: [
      { label: 'Living room', place: 'Villa · Al Nakheel', time: '3h 20m', team: '2 specialists', work: 'Rug shampoo, upholstery steam, glass & skirting detail' },
      { label: 'Kitchen', place: 'Apartment · Al Olaya', time: '2h 45m', team: '2 specialists', work: 'Degreasing, appliance detail, counter & floor restoration' },
      { label: 'Bathroom', place: 'Villa · Hittin', time: '1h 50m', team: '1 specialist', work: 'Limescale & mildew removal, grout and glass polish' },
    ],
  },
  howItWorks: {
    eyebrow: 'How it works',
    line1: 'Three steps.',
    soft: 'zero ',
    bold: 'effort.',
    intro: 'Booking takes two minutes. Everything after that is on us.',
    steps: [
      {
        title: 'Book in two minutes',
        text: 'Choose the service, your district and a time that suits you. You get a fixed price up front. No calls, no surprises.',
        points: ['Same-day slots across Riyadh', 'Fixed, transparent pricing'],
      },
      {
        title: 'We arrive and transform',
        text: 'A vetted, insured team arrives fully equipped: industrial steam, HEPA extraction and eco-certified products.',
        points: ['Background-checked specialists', 'Safe for children and pets'],
      },
      {
        title: 'Walk into spotless',
        text: 'We finish with a walkthrough together. If anything is less than perfect, we come back and re-clean it free within 24 hours.',
        points: ['Room-by-room inspection', '100% satisfaction guarantee'],
      },
    ],
  },
  testimonials: {
    eyebrow: 'Kind words',
    from: 'from 1,200+ homes in Riyadh',
    quoteMark: '“',
    showReview: 'Show review from {name}',
    prev: 'Previous review',
    next: 'Next review',
    starsAria: '{n} out of 5 stars',
    reviews: [
      { name: 'Noura A.', place: 'Villa · Hittin', service: 'Villa deep clean', quote: 'They gave us back the house we moved into. Every corner, every grout line, even the majlis carpets look new again.' },
      { name: 'Faisal M.', place: 'Apartment · Al Olaya', service: 'Move-out clean', quote: 'Booked at nine, the team was at my door before eleven. My landlord asked who I’d hired and kept the number.' },
      { name: 'Sarah K.', place: 'Villa · Al Malqa', service: 'Post-construction', quote: 'After six months of renovation dust I had honestly given up. Two days later the whole villa was spotless, and quiet.' },
      { name: 'Abdullah R.', place: 'Office · King Fahd Road', service: 'Weekly office care', quote: 'Our office has never felt this fresh. Discreet, always on time, and the same trusted crew every single week.' },
      { name: 'Lina H.', place: 'Villa · Al Yasmin', service: 'Marble & upholstery', quote: 'The marble floors gleam like a hotel lobby. The sofa my kids live on? You would never know.' },
    ],
    snippets: [
      ['Like moving into a new villa.', 'Noura · Hittin'],
      ['On time, every time.', 'Abdullah · Olaya'],
      ['The majlis smells like the first day.', 'Reem · Al Narjis'],
      ['Worth every riyal.', 'Faisal · Al Olaya'],
      ['My mother noticed the windows first.', 'Omar · Al Rabwah'],
      ['Spotless and genuinely kind people.', 'Sarah · Al Malqa'],
    ],
  },
  booking: {
    eyebrow: 'Riyadh premier cleaning specialists',
    line1: 'Transform your space',
    soft: 'in just ',
    bold: 'one hour.',
    intro:
      'Book Riyadh’s top-rated cleaning and maintenance team. We arrive with industrial equipment and eco-certified products, and every visit is backed by our 100% satisfaction guarantee.',
    stats: [
      { value: '4.9/5', label: 'Average client rating' },
      { value: '1,200+', label: 'Homes cleaned in Riyadh' },
      { value: '90 min', label: 'Same-day arrival across Riyadh' },
      { value: '100%', label: 'Satisfaction, or a free re-clean' },
    ],
    contactTitle: 'Riyadh dispatch desk',
    reassure: 'Our dispatch team calls you within 15 minutes to confirm.',
    address: 'King Fahd Road, Al Olaya, Riyadh 12211, Saudi Arabia',
    formTitle: 'Book FreshSpaces Cleaning',
    formIntro: 'Get an instant quote and priority dispatch date.',
    name: 'Your Name',
    namePlaceholder: 'e.g. Osama Tillo',
    phone: 'Mobile Number',
    district: 'Riyadh District',
    districts: ['Al Malqa, Riyadh', 'Al Nakheel, Riyadh', 'Hittin, Riyadh', 'Al Olaya, Riyadh', 'Al Yasmin, Riyadh', 'Other Riyadh Location'],
    service: 'Service Type',
    notes: 'Special Requests (Optional)',
    notesPlaceholder: 'Specify size of property, number of bedrooms, or specific requirements...',
    submit: 'Confirm Cleaning Booking',
    doneTitle: 'Booking Request Received!',
    done: ['Thank you, ', '. Our Riyadh dispatch team will call you at ', ' within 15 minutes.'],
    again: 'Submit Another Request',
  },
  footer: {
    servicesTitle: 'Services',
    hqTitle: 'Riyadh Dispatch HQ',
    address: 'King Fahd Road, Al Olaya District, Riyadh, Kingdom of Saudi Arabia',
    hotline: '24/7 Emergency Cleaning Hotline',
    licensed: 'Licensed Saudi Commercial CR #101089201',
    backToTop: 'Back to top',
  },
};
